### A. EXTRACT

In [1]:
import pandas as pd
from selenium import webdriver
from bs4 import BeautifulSoup
import time

driver = webdriver.Chrome()
# Pembuatan kolom kosong yang digunakan untuk menambahkan dari data yang sudah dilooping
nama_produk = []
harga_produk = []
rating_produk = []
foto_produk = []

# Proses pengambilan data dari halaman 1-4 dari website yang dipilih
for hal in range (1,5): # Loop untuk pengambilan data dihalaman yang ditentukan
    url = f'https://jdsports.id/search/shoes?page={hal}'
    driver.get(url)
    time.sleep(5) # Untuk memberikan jeda waktu 5 detik membuka website sebelum dicapture

    html = driver.page_source
    soup = BeautifulSoup(html, "html.parser")

    boxes = soup.find_all('div',{'class':'relative cursor-pointer card-product h-full bg-white'})

# Query untuk melakukan looping dan mengakses satu per satu data dan memasukan ke dalam lists kosong yang sudah dibuat
    for box in boxes:
        nama_ecer = box.find('div',{'class':'text-sm w-[85%] ellipsis-2 md:text-xs sm:text-[10px] hover:underline'})
        try:
            nama_produk.append(nama_ecer.get_text())
        except:
            nama_produk.append(None)

        harga_ecer = box.find('span',{'class':'font-bold'})
        try:
            harga_produk.append(harga_ecer.get_text())
        except:
            harga_produk.append(None)

        rating_ecer = box.find('p',{'class':'text-[12px] sm:text-[10px] font-normal tracking-[0.1rem]'})
        try:
            rating_produk.append(rating_ecer.get_text())
        except:
            rating_produk.append(None)

        foto_ecer = box.find('img',{'class':'absolute inset-0 z-0 object-cover object-center w-full h-full opacity-0 group-hover:opacity-100 transition-opacity duration-500'})
        try:
            foto_produk.append(foto_ecer['src'])
        except:
            foto_produk.append(None)
      
# Membuat dataframe untuk diisi dengan lists yang sudah mempunyai data dari looping
df = pd.DataFrame({
'Produk' : nama_produk,
'Harga' : harga_produk,
'Rating' : rating_produk,
'Foto' : foto_produk
})

# Query untuk menyimpan data yang sudah di scraping dari website ke dalam format csv
df.to_csv('CODA_P0M1_Kenny-Palibutan_KOTOR.csv')

In [2]:
df

,Produk,Harga,Rating,Foto
0,Nike V5 RNR Women's,Rp 1.399.000,None,/_next/image?url=https%3A%2F%2Fimages.jdsports...
1,Nike Vomero 5 Junior,Rp 1.299.000,(5/5),/_next/image?url=https%3A%2F%2Fimages.jdsports...
2,On Cloudsurfer Next,Rp 2.500.000,(5/5),/_next/image?url=https%3A%2F%2Fimages.jdsports...
3,New Balance 740 Children,Rp 1.199.000,None,/_next/image?url=https%3A%2F%2Fimages.jdsports...
4,adidas Originals Samba OG Children,Rp 850.000,None,/_next/image?url=https%3A%2F%2Fimages.jdsports...
...,...,...,...,...
139,Salomon ACS+ OG,Rp 3.499.000,None,/_next/image?url=https%3A%2F%2Fimages.jdsports...
140,Salomon XT 6,Rp 3.899.000,None,/_next/image?url=https%3A%2F%2Fimages.jdsports...
141,Salomon XT 6,Rp 3.899.000,None,/_next/image?url=https%3A%2F%2Fimages.jdsports...
142,adidas Adizero Evo SL,Rp 2.500.000,(5/5),/_next/image?url=https%3A%2F%2Fimages.jdsports...
143,adidas Adizero Evo SL,Rp 2.500.000,(5/5),/_next/image?url=https%3A%2F%2Fimages.jdsports...

### B. TRANSFORM

### Query untuk menghapus data yang mempunyai value tidak sesuai

In [3]:
df[~(df['Harga']=='JD Exclusive')].head(50)
df = df[~(df['Harga']=='JD Exclusive')].head(50)

In [4]:
df

,Produk,Harga,Rating,Foto
0,Nike V5 RNR Women's,Rp 1.399.000,None,/_next/image?url=https%3A%2F%2Fimages.jdsports...
1,Nike Vomero 5 Junior,Rp 1.299.000,(5/5),/_next/image?url=https%3A%2F%2Fimages.jdsports...
2,On Cloudsurfer Next,Rp 2.500.000,(5/5),/_next/image?url=https%3A%2F%2Fimages.jdsports...
3,New Balance 740 Children,Rp 1.199.000,None,/_next/image?url=https%3A%2F%2Fimages.jdsports...
4,adidas Originals Samba OG Children,Rp 850.000,None,/_next/image?url=https%3A%2F%2Fimages.jdsports...
5,Nike Vomero 5 Junior,Rp 1.499.000,None,/_next/image?url=https%3A%2F%2Fimages.jdsports...
6,New Balance 530 Women's,Rp 1.699.000,(5/5),/_next/image?url=https%3A%2F%2Fimages.jdsports...
7,On Cloudtilt,Rp 2.700.000,None,/_next/image?url=https%3A%2F%2Fimages.jdsports...
8,New Balance 530,Rp 1.699.000,(5/5),/_next/image?url=https%3A%2F%2Fimages.jdsports...
9,Salomon XT 6 Expanse,Rp 3.499.000,None,/_next/image?url=https%3A%2F%2Fimages.jdsports...
10,adidas Originals Samba OG Junior,Rp 1.100.000,None,/_next/image?url=https%3A%2F%2Fimages.jdsports...
12,Asics Gel Kayano 14,Rp 2.399.000,(5/5),/_next/image?url=https%3A%2F%2Fimages.jdsports...
13,Jordan Air 1 Low Infant,Rp 729.000,None,/_next/image?url=https%3A%2F%2Fimages.jdsports...
14,On Cloudvista 2 Women's,Rp 2.500.000,None,/_next/image?url=https%3A%2F%2Fimages.jdsports...
15,On Cloud 6,Rp 2.500.000,(5/5),/_next/image?url=https%3A%2F%2Fimages.jdsports...
16,New Balance 740,Rp 1.799.000,(5/5),/_next/image?url=https%3A%2F%2Fimages.jdsports...
17,Nike Air Max Moto,Rp 1.999.000,(5/5),/_next/image?url=https%3A%2F%2Fimages.jdsports...
18,On Cloudswift Junior,Rp 1.800.000,(5/5),/_next/image?url=https%3A%2F%2Fimages.jdsports...
19,Asics Gel-Nunobiki White Ribbon Laces,Rp 1.699.000,(5/5),/_next/image?url=https%3A%2F%2Fimages.jdsports...
20,New Balance 740 Women's,Rp 1.899.000,(5/5),/_next/image?url=https%3A%2F%2Fimages.jdsports...
21,New Balance 530 Children,Rp 1.099.000,(5/5),/_next/image?url=https%3A%2F%2Fimages.jdsports...
22,New Balance 740 Children,Rp 1.199.000,None,/_next/image?url=https%3A%2F%2Fimages.jdsports...
23,On Cloud 6 Women's,Rp 2.500.000,(5/5),/_next/image?url=https%3A%2F%2Fimages.jdsports...
24,New Balance 530 Children,Rp 1.099.000,None,/_next/image?url=https%3A%2F%2Fimages.jdsports...
25,On Cloudtilt Women's,Rp 2.700.000,(5/5),/_next/image?url=https%3A%2F%2Fimages.jdsports...
26,On Cloudmonster Void,Rp 3.000.000,None,/_next/image?url=https%3A%2F%2Fimages.jdsports...
27,On Cloud 6,Rp 2.500.000,None,/_next/image?url=https%3A%2F%2Fimages.jdsports...
28,On Cloud 6,Rp 2.500.000,(5/5),/_next/image?url=https%3A%2F%2Fimages.jdsports...
29,On Cloud 6 Waterproof,Rp 2.900.000,(5/5),/_next/image?url=https%3A%2F%2Fimages.jdsports...
30,On Cloudvista 2,Rp 2.500.000,(5/5),/_next/image?url=https%3A%2F%2Fimages.jdsports...
31,On Cloudtilt,Rp 2.700.000,(5/5),/_next/image?url=https%3A%2F%2Fimages.jdsports...
32,Nike Rejuven 8,Rp 1.069.000,None,/_next/image?url=https%3A%2F%2Fimages.jdsports...
33,New Balance 530,Rp 1.699.000,(5/5),/_next/image?url=https%3A%2F%2Fimages.jdsports...
34,Nike P-6000,Rp 1.429.000,(5/5),/_next/image?url=https%3A%2F%2Fimages.jdsports...
35,adidas Originals Bermuda Women's,Rp 1.700.000,None,/_next/image?url=https%3A%2F%2Fimages.jdsports...
36,Nike Vomero 5,Rp 2.489.000,None,/_next/image?url=https%3A%2F%2Fimages.jdsports...
37,On Cloud 6,Rp 2.500.000,(5/5),/_next/image?url=https%3A%2F%2Fimages.jdsports...
38,Asics Gel Nyc Steel Women's,Rp 2.299.000,None,/_next/image?url=https%3A%2F%2Fimages.jdsports...
39,On Cloudtilt Women's,Rp 2.700.000,(5/5),/_next/image?url=https%3A%2F%2Fimages.jdsports...
40,Nike V5 RNR Women's,Rp 1.399.000,None,/_next/image?url=https%3A%2F%2Fimages.jdsports...
41,New Balance 204L,Rp 1.699.000,(5/5),/_next/image?url=https%3A%2F%2Fimages.jdsports...
42,On Cloudmonster,Rp 3.000.000,(5/5),/_next/image?url=https%3A%2F%2Fimages.jdsports...
43,On Cloudmonster Void,Rp 3.000.000,(5/5),/_next/image?url=https%3A%2F%2Fimages.jdsports...
44,On Cloudsurfer,Rp 2.500.000,None,/_next/image?url=https%3A%2F%2Fimages.jdsports...
45,Nike Vomero 18,Rp 2.249.000,None,/_next/image?url=https%3A%2F%2Fimages.jdsports...
46,Nike Vomero 18,Rp 2.249.000,None,/_next/image?url=https%3A%2F%2Fimages.jdsports...
47,Nike Journey Run,Rp 1.399.000,None,/_next/image?url=https%3A%2F%2Fimages.jdsports...
48,Nike Journey Run,Rp 1.399.000,None,/_next/image?url=https%3A%2F%2Fimages.jdsports...
49,Jordan Air 1 Brooklyn Women's,Rp 2.629.000,None,/_next/image?url=https%3A%2F%2Fimages.jdsports...
50,Nike Air Max 95,Rp 2.849.000,(5/5),/_next/image?url=https%3A%2F%2Fimages.jdsports...

### Query untuk merubah format penulisan kolom harga menjadi hanya angka dengan tipe data integer

In [5]:
df['Harga'].str.replace('Rp','')
df['Harga'] = df['Harga'].str.replace('Rp','')
df['Harga'].str.replace('.','')
df['Harga'] = df['Harga'].str.replace('.','')
df['Harga'].astype(int)
df['Harga'] = df['Harga'].astype(int)

df

,Produk,Harga,Rating,Foto
0,Nike V5 RNR Women's,1399000,None,/_next/image?url=https%3A%2F%2Fimages.jdsports...
1,Nike Vomero 5 Junior,1299000,(5/5),/_next/image?url=https%3A%2F%2Fimages.jdsports...
2,On Cloudsurfer Next,2500000,(5/5),/_next/image?url=https%3A%2F%2Fimages.jdsports...
3,New Balance 740 Children,1199000,None,/_next/image?url=https%3A%2F%2Fimages.jdsports...
4,adidas Originals Samba OG Children,850000,None,/_next/image?url=https%3A%2F%2Fimages.jdsports...
5,Nike Vomero 5 Junior,1499000,None,/_next/image?url=https%3A%2F%2Fimages.jdsports...
6,New Balance 530 Women's,1699000,(5/5),/_next/image?url=https%3A%2F%2Fimages.jdsports...
7,On Cloudtilt,2700000,None,/_next/image?url=https%3A%2F%2Fimages.jdsports...
8,New Balance 530,1699000,(5/5),/_next/image?url=https%3A%2F%2Fimages.jdsports...
9,Salomon XT 6 Expanse,3499000,None,/_next/image?url=https%3A%2F%2Fimages.jdsports...
10,adidas Originals Samba OG Junior,1100000,None,/_next/image?url=https%3A%2F%2Fimages.jdsports...
12,Asics Gel Kayano 14,2399000,(5/5),/_next/image?url=https%3A%2F%2Fimages.jdsports...
13,Jordan Air 1 Low Infant,729000,None,/_next/image?url=https%3A%2F%2Fimages.jdsports...
14,On Cloudvista 2 Women's,2500000,None,/_next/image?url=https%3A%2F%2Fimages.jdsports...
15,On Cloud 6,2500000,(5/5),/_next/image?url=https%3A%2F%2Fimages.jdsports...
16,New Balance 740,1799000,(5/5),/_next/image?url=https%3A%2F%2Fimages.jdsports...
17,Nike Air Max Moto,1999000,(5/5),/_next/image?url=https%3A%2F%2Fimages.jdsports...
18,On Cloudswift Junior,1800000,(5/5),/_next/image?url=https%3A%2F%2Fimages.jdsports...
19,Asics Gel-Nunobiki White Ribbon Laces,1699000,(5/5),/_next/image?url=https%3A%2F%2Fimages.jdsports...
20,New Balance 740 Women's,1899000,(5/5),/_next/image?url=https%3A%2F%2Fimages.jdsports...
21,New Balance 530 Children,1099000,(5/5),/_next/image?url=https%3A%2F%2Fimages.jdsports...
22,New Balance 740 Children,1199000,None,/_next/image?url=https%3A%2F%2Fimages.jdsports...
23,On Cloud 6 Women's,2500000,(5/5),/_next/image?url=https%3A%2F%2Fimages.jdsports...
24,New Balance 530 Children,1099000,None,/_next/image?url=https%3A%2F%2Fimages.jdsports...
25,On Cloudtilt Women's,2700000,(5/5),/_next/image?url=https%3A%2F%2Fimages.jdsports...
26,On Cloudmonster Void,3000000,None,/_next/image?url=https%3A%2F%2Fimages.jdsports...
27,On Cloud 6,2500000,None,/_next/image?url=https%3A%2F%2Fimages.jdsports...
28,On Cloud 6,2500000,(5/5),/_next/image?url=https%3A%2F%2Fimages.jdsports...
29,On Cloud 6 Waterproof,2900000,(5/5),/_next/image?url=https%3A%2F%2Fimages.jdsports...
30,On Cloudvista 2,2500000,(5/5),/_next/image?url=https%3A%2F%2Fimages.jdsports...
31,On Cloudtilt,2700000,(5/5),/_next/image?url=https%3A%2F%2Fimages.jdsports...
32,Nike Rejuven 8,1069000,None,/_next/image?url=https%3A%2F%2Fimages.jdsports...
33,New Balance 530,1699000,(5/5),/_next/image?url=https%3A%2F%2Fimages.jdsports...
34,Nike P-6000,1429000,(5/5),/_next/image?url=https%3A%2F%2Fimages.jdsports...
35,adidas Originals Bermuda Women's,1700000,None,/_next/image?url=https%3A%2F%2Fimages.jdsports...
36,Nike Vomero 5,2489000,None,/_next/image?url=https%3A%2F%2Fimages.jdsports...
37,On Cloud 6,2500000,(5/5),/_next/image?url=https%3A%2F%2Fimages.jdsports...
38,Asics Gel Nyc Steel Women's,2299000,None,/_next/image?url=https%3A%2F%2Fimages.jdsports...
39,On Cloudtilt Women's,2700000,(5/5),/_next/image?url=https%3A%2F%2Fimages.jdsports...
40,Nike V5 RNR Women's,1399000,None,/_next/image?url=https%3A%2F%2Fimages.jdsports...
41,New Balance 204L,1699000,(5/5),/_next/image?url=https%3A%2F%2Fimages.jdsports...
42,On Cloudmonster,3000000,(5/5),/_next/image?url=https%3A%2F%2Fimages.jdsports...
43,On Cloudmonster Void,3000000,(5/5),/_next/image?url=https%3A%2F%2Fimages.jdsports...
44,On Cloudsurfer,2500000,None,/_next/image?url=https%3A%2F%2Fimages.jdsports...
45,Nike Vomero 18,2249000,None,/_next/image?url=https%3A%2F%2Fimages.jdsports...
46,Nike Vomero 18,2249000,None,/_next/image?url=https%3A%2F%2Fimages.jdsports...
47,Nike Journey Run,1399000,None,/_next/image?url=https%3A%2F%2Fimages.jdsports...
48,Nike Journey Run,1399000,None,/_next/image?url=https%3A%2F%2Fimages.jdsports...
49,Jordan Air 1 Brooklyn Women's,2629000,None,/_next/image?url=https%3A%2F%2Fimages.jdsports...
50,Nike Air Max 95,2849000,(5/5),/_next/image?url=https%3A%2F%2Fimages.jdsports...

### Query untuk merubah format penulisan kolom Rating menjadi hanya angka dengan tipe data integer

In [6]:
df['Rating'].str.split('/').str[0]
df['Rating'] = df['Rating'].str.split('/').str[0]
df['Rating'].str.replace('(','')
df['Rating'] = df['Rating'].str.replace('(','')
df['Rating'] = df['Rating'].fillna(0).astype(int)

In [7]:
df

,Produk,Harga,Rating,Foto
0,Nike V5 RNR Women's,1399000,0,/_next/image?url=https%3A%2F%2Fimages.jdsports...
1,Nike Vomero 5 Junior,1299000,5,/_next/image?url=https%3A%2F%2Fimages.jdsports...
2,On Cloudsurfer Next,2500000,5,/_next/image?url=https%3A%2F%2Fimages.jdsports...
3,New Balance 740 Children,1199000,0,/_next/image?url=https%3A%2F%2Fimages.jdsports...
4,adidas Originals Samba OG Children,850000,0,/_next/image?url=https%3A%2F%2Fimages.jdsports...
5,Nike Vomero 5 Junior,1499000,0,/_next/image?url=https%3A%2F%2Fimages.jdsports...
6,New Balance 530 Women's,1699000,5,/_next/image?url=https%3A%2F%2Fimages.jdsports...
7,On Cloudtilt,2700000,0,/_next/image?url=https%3A%2F%2Fimages.jdsports...
8,New Balance 530,1699000,5,/_next/image?url=https%3A%2F%2Fimages.jdsports...
9,Salomon XT 6 Expanse,3499000,0,/_next/image?url=https%3A%2F%2Fimages.jdsports...
10,adidas Originals Samba OG Junior,1100000,0,/_next/image?url=https%3A%2F%2Fimages.jdsports...
12,Asics Gel Kayano 14,2399000,5,/_next/image?url=https%3A%2F%2Fimages.jdsports...
13,Jordan Air 1 Low Infant,729000,0,/_next/image?url=https%3A%2F%2Fimages.jdsports...
14,On Cloudvista 2 Women's,2500000,0,/_next/image?url=https%3A%2F%2Fimages.jdsports...
15,On Cloud 6,2500000,5,/_next/image?url=https%3A%2F%2Fimages.jdsports...
16,New Balance 740,1799000,5,/_next/image?url=https%3A%2F%2Fimages.jdsports...
17,Nike Air Max Moto,1999000,5,/_next/image?url=https%3A%2F%2Fimages.jdsports...
18,On Cloudswift Junior,1800000,5,/_next/image?url=https%3A%2F%2Fimages.jdsports...
19,Asics Gel-Nunobiki White Ribbon Laces,1699000,5,/_next/image?url=https%3A%2F%2Fimages.jdsports...
20,New Balance 740 Women's,1899000,5,/_next/image?url=https%3A%2F%2Fimages.jdsports...
21,New Balance 530 Children,1099000,5,/_next/image?url=https%3A%2F%2Fimages.jdsports...
22,New Balance 740 Children,1199000,0,/_next/image?url=https%3A%2F%2Fimages.jdsports...
23,On Cloud 6 Women's,2500000,5,/_next/image?url=https%3A%2F%2Fimages.jdsports...
24,New Balance 530 Children,1099000,0,/_next/image?url=https%3A%2F%2Fimages.jdsports...
25,On Cloudtilt Women's,2700000,5,/_next/image?url=https%3A%2F%2Fimages.jdsports...
26,On Cloudmonster Void,3000000,0,/_next/image?url=https%3A%2F%2Fimages.jdsports...
27,On Cloud 6,2500000,0,/_next/image?url=https%3A%2F%2Fimages.jdsports...
28,On Cloud 6,2500000,5,/_next/image?url=https%3A%2F%2Fimages.jdsports...
29,On Cloud 6 Waterproof,2900000,5,/_next/image?url=https%3A%2F%2Fimages.jdsports...
30,On Cloudvista 2,2500000,5,/_next/image?url=https%3A%2F%2Fimages.jdsports...
31,On Cloudtilt,2700000,5,/_next/image?url=https%3A%2F%2Fimages.jdsports...
32,Nike Rejuven 8,1069000,0,/_next/image?url=https%3A%2F%2Fimages.jdsports...
33,New Balance 530,1699000,5,/_next/image?url=https%3A%2F%2Fimages.jdsports...
34,Nike P-6000,1429000,5,/_next/image?url=https%3A%2F%2Fimages.jdsports...
35,adidas Originals Bermuda Women's,1700000,0,/_next/image?url=https%3A%2F%2Fimages.jdsports...
36,Nike Vomero 5,2489000,0,/_next/image?url=https%3A%2F%2Fimages.jdsports...
37,On Cloud 6,2500000,5,/_next/image?url=https%3A%2F%2Fimages.jdsports...
38,Asics Gel Nyc Steel Women's,2299000,0,/_next/image?url=https%3A%2F%2Fimages.jdsports...
39,On Cloudtilt Women's,2700000,5,/_next/image?url=https%3A%2F%2Fimages.jdsports...
40,Nike V5 RNR Women's,1399000,0,/_next/image?url=https%3A%2F%2Fimages.jdsports...
41,New Balance 204L,1699000,5,/_next/image?url=https%3A%2F%2Fimages.jdsports...
42,On Cloudmonster,3000000,5,/_next/image?url=https%3A%2F%2Fimages.jdsports...
43,On Cloudmonster Void,3000000,5,/_next/image?url=https%3A%2F%2Fimages.jdsports...
44,On Cloudsurfer,2500000,0,/_next/image?url=https%3A%2F%2Fimages.jdsports...
45,Nike Vomero 18,2249000,0,/_next/image?url=https%3A%2F%2Fimages.jdsports...
46,Nike Vomero 18,2249000,0,/_next/image?url=https%3A%2F%2Fimages.jdsports...
47,Nike Journey Run,1399000,0,/_next/image?url=https%3A%2F%2Fimages.jdsports...
48,Nike Journey Run,1399000,0,/_next/image?url=https%3A%2F%2Fimages.jdsports...
49,Jordan Air 1 Brooklyn Women's,2629000,0,/_next/image?url=https%3A%2F%2Fimages.jdsports...
50,Nike Air Max 95,2849000,5,/_next/image?url=https%3A%2F%2Fimages.jdsports...

### Query untuk mengecek informasi setiap kolom pada datafram dan memastikan untuk tipe data setiap kolom sudah sesuai

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 50 entries, 0 to 50
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Produk  50 non-null     object
 1   Harga   50 non-null     int64
 2   Rating  50 non-null     int64
 3   Foto    50 non-null     object
dtypes: int64(2), object(2)
memory usage: 2.0+ KB

### Query untuk menyimpan data yang sudah diolah ke dalam format csv

In [9]:
df.to_csv('CODA_P0M1_Kenny-Palibutan_BERSIH.csv')